-- Create todos table
CREATE TABLE IF NOT EXISTS public.todos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    content text,
    user_id text,
    is_complete boolean DEFAULT false
);